source 'http://rubygems.org'
gem 'sinatra'
gem 'sinatra-reloader'
#gem 'ruby-libvirt'
gem 'haml'
gem 'sass'
gem 'coffee-script'
gem 'rspec'
gem 'rubocop'
gem "sqlite3"
gem "activerecord"
gem "ruby-libvirt"
gem "parallel"
gem "test-unit"
